apiVersion: v1
kind: Service
metadata:
  name: percona-pmm
spec:
  selector:
    name: percona-server-mongodb-operator
  ports:
    - port: 60000
      targetPort: 60000
  type: LoadBalancer
